---
- name: Setup database
  hosts: database
  become: yes
  tasks:
    - name: update 
      apt:
        update_cache: yes
    - name: upgrade
      apt:
        upgrade: dist

    - name: Install software 
      apt:
        name: 
          - mysql-server
          - python3-pip

    - name: Pip install pyMySQL
      pip:
        name: pymysql
 

    - name: Create Wordpress database
      community.mysql.mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock 
        name: wordpress
        state: import
        target: /vagrant/wordpress.sql
        force: yes

    - name: Adjust mysql configuration file 
      replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "127.0.0.1"
        replace: "0.0.0.0"

    - name: Make sure mysql is running
      service:
        name: mysql 
        state: restarted